"""Automatic experiment-to-simulation comparison for registered tuning states."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

import numpy as np
import pandas as pd

from deflector_tuning.analysis.phase_radius_equivalence import (
    PhaseRadiusMappingError,
    build_experiment_simulation_phase_comparison,
    fit_rc_states,
)
from deflector_tuning.project_defaults import DEFAULT_PROJECT_DEFAULTS, ProjectDefaults
from deflector_tuning.runner import run_folder_analysis
from deflector_tuning.tuning_campaign import (
    PhaseReference,
    SimulationReference,
    TuningCampaignMatch,
)
from deflector_tuning.visualization.grid_scan_phase_line_plots import (
    plot_phase_rc_map,
)
from deflector_tuning.visualization.phase_radius_equivalence_plots import plot_phase_cmp_bars
from deflector_tuning.workflows.manifest import register_tuning_cmp
from deflector_tuning.workflows.models import RunResult


logger = logging.getLogger(__name__)


REQUIRED_MARKER_COLUMNS = (
    "source_file",
    "tune_position",
    "marker_name",
    "s_phase_deg",
)


@dataclass(frozen=True)
class TuningFamilyComparison:
    """Derived comparison products for one measurement family."""

    family: str
    anchor_check: pd.DataFrame
    rc_fit: pd.DataFrame
    phase_cmp: pd.DataFrame
    simulation_line: pd.DataFrame


@dataclass(frozen=True)
class TuningCmpResult:
    """Files generated by one automatic tuning comparison."""

    tables: Mapping[str, Path]
    figures: Mapping[str, Path]
    families: tuple[str, ...]
    skipped_families: tuple[str, ...]


def measurement_family_for_position(position: float, *, tolerance: float = 1e-6) -> str:
    """Classify integer positions as iris and half-integers as cell."""

    value = float(position)
    if abs(value - round(value)) <= tolerance:
        return "iris"
    if abs(value * 2.0 - round(value * 2.0)) <= tolerance:
        return "cell"
    raise ValueError(f"Unsupported measurement position {position!r}")


def build_anchor_check(
    marker_table: pd.DataFrame,
    *,
    position: float,
    expected_phase_deg: float = 180.0,
    tolerance_deg: float = 5.0,
    marker_name: str = "f_mean",
    port_extension_applied: bool = True,
) -> pd.DataFrame:
    """Check that a port-extended reference position is close to 180 degrees."""

    selected = _select_position_markers(
        marker_table,
        position=position,
        port_extension_applied=port_extension_applied,
    )
    selected = selected[selected["marker_name"] == marker_name].copy()
    if len(selected) != 1:
        raise ValueError(
            f"Expected one {marker_name} row at position {position:g}; found {len(selected)}"
        )
    selected["expected_phase_deg"] = float(expected_phase_deg)
    selected["phase_error_deg"] = _wrap180(
        selected["s_phase_deg"].to_numpy(dtype=float) - expected_phase_deg
    )
    selected["tolerance_deg"] = float(tolerance_deg)
    selected["verified"] = selected["phase_error_deg"].abs() <= tolerance_deg
    return selected.reset_index(drop=True)


def build_position_phase_change(
    before_marker_table: pd.DataFrame,
    after_marker_table: pd.DataFrame,
    *,
    position: float,
    port_extension_applied: bool = True,
) -> pd.DataFrame:
    """Return wrapped experimental phase change at one configured position."""

    before = _select_position_markers(
        before_marker_table,
        position=position,
        port_extension_applied=port_extension_applied,
    ).loc[:, ["marker_name", "source_file", "s_phase_deg"]]
    after = _select_position_markers(
        after_marker_table,
        position=position,
        port_extension_applied=port_extension_applied,
    ).loc[:, ["marker_name", "source_file", "s_phase_deg"]]
    merged = before.merge(
        after,
        on="marker_name",
        suffixes=("_before", "_after"),
        validate="one_to_one",
    )
    if merged.empty:
        raise ValueError(f"No shared marker phases at position {position:g}")
    merged.insert(0, "tune_position", float(position))
    merged["phase_delta_deg"] = _wrap180(
        merged["s_phase_deg_after"].to_numpy(dtype=float)
        - merged["s_phase_deg_before"].to_numpy(dtype=float)
    )
    return merged


def build_tuning_family_comparison(
    simulation_marker_table: pd.DataFrame,
    baseline_marker_table: pd.DataFrame,
    current_marker_table: pd.DataFrame,
    *,
    reference: SimulationReference,
    phase_reference: PhaseReference,
    design_r_c_mm: float,
) -> TuningFamilyComparison:
    """Fit equivalent baseline/current states and compare them with simulation."""

    if reference.axis != "r_c":
        raise ValueError(
            f"Automatic tuning comparison requires axis='r_c'; got {reference.axis!r}"
        )
    if len(reference.experiment_positions) < 2:
        raise ValueError(
            f"Simulation reference {reference.family!r} needs anchor and comparison positions"
        )
    anchor_position = reference.experiment_positions[0]
    comparison_position = reference.experiment_positions[1]
    port_extension_applied = phase_reference.port_extension == "applied"
    baseline_anchor = build_anchor_check(
        baseline_marker_table,
        position=anchor_position,
        expected_phase_deg=phase_reference.anchor_phase_deg,
        tolerance_deg=phase_reference.anchor_tolerance_deg,
        marker_name=phase_reference.anchor_marker,
        port_extension_applied=port_extension_applied,
    ).assign(state="baseline")
    current_anchor = build_anchor_check(
        current_marker_table,
        position=anchor_position,
        expected_phase_deg=phase_reference.anchor_phase_deg,
        tolerance_deg=phase_reference.anchor_tolerance_deg,
        marker_name=phase_reference.anchor_marker,
        port_extension_applied=port_extension_applied,
    ).assign(state="current")
    anchor_check = pd.concat(
        [baseline_anchor, current_anchor],
        ignore_index=True,
    )

    phase_change = build_position_phase_change(
        baseline_marker_table,
        current_marker_table,
        position=comparison_position,
        port_extension_applied=port_extension_applied,
    )
    phase_change.insert(0, "family", reference.family)

    simulation_line = _simulation_rc_line(
        simulation_marker_table,
        marker_names=phase_change["marker_name"].astype(str).tolist(),
    )
    observation = phase_change.rename(
        columns={
            "s_phase_deg_before": "before_phase_deg",
            "s_phase_deg_after": "after_phase_deg",
        }
    ).loc[:, ["marker_name", "before_phase_deg", "after_phase_deg"]]
    rc_fit = fit_rc_states(
        simulation_line,
        observation,
        design_r_c_mm=design_r_c_mm,
        anchor_marker=phase_reference.anchor_marker,
    )
    radii = rc_fit.set_index("state")["r_c_mm"]
    phase_cmp = build_experiment_simulation_phase_comparison(
        simulation_line,
        observation,
        before_r_c_mm=float(radii["baseline"]),
        current_r_c_mm=float(radii["current"]),
    )
    interpretation = "simulation-equivalent coordinate; not physical bolt travel"
    rc_fit.insert(0, "family", reference.family)
    rc_fit["interpretation"] = interpretation
    phase_cmp.insert(0, "family", reference.family)
    anchor_check.insert(0, "family", reference.family)
    return TuningFamilyComparison(
        family=reference.family,
        anchor_check=anchor_check,
        rc_fit=rc_fit,
        phase_cmp=phase_cmp,
        simulation_line=simulation_line,
    )


def run_tuning_cmp(
    campaign_match: TuningCampaignMatch,
    *,
    current_result: RunResult,
    data_root: str | Path,
    file_workers: int = 1,
    plot_workers: int = 1,
    project_defaults: ProjectDefaults = DEFAULT_PROJECT_DEFAULTS,
) -> TuningCmpResult:
    """Generate automatic comparison outputs for one registered tuning state."""

    if campaign_match.state_id is None:
        raise ValueError("A tuning-state match is required for experiment comparison")
    campaign = campaign_match.campaign
    current_state = campaign.states[campaign_match.state_id]
    baseline_state = campaign.states[campaign.baseline_state_id]
    if current_state.dataset is None or baseline_state.dataset is None:
        raise ValueError("Current and baseline tuning states require datasets")

    data_root = Path(data_root)
    analysis_root = Path(current_result.output_dir).parent
    current_marker_path = _marker_table_path(current_result)
    current_markers = pd.read_csv(current_marker_path)
    baseline_markers = _ensure_marker_table(
        baseline_state.dataset,
        layer="raw",
        marker_role="exp",
        data_root=data_root,
        analysis_root=analysis_root,
        file_workers=file_workers,
        plot_workers=plot_workers,
        project_defaults=project_defaults,
    )

    output_table_dir = Path(current_result.output_dir) / "tables"
    output_figure_dir = (
        Path(current_result.output_dir) / "figures" / "tuning_cmp"
    )
    output_table_dir.mkdir(parents=True, exist_ok=True)
    output_figure_dir.mkdir(parents=True, exist_ok=True)

    table_paths: dict[str, Path] = {}
    figure_paths: dict[str, Path] = {}
    completed_families: list[str] = []
    skipped_families: list[str] = []
    skipped_family_reasons: dict[str, str] = {}
    for family, reference in campaign.simulation_references.items():
        if not _table_contains_positions(
            current_markers,
            reference.experiment_positions[:2],
        ):
            logger.info(
                "Skipping %s tuning comparison; current dataset lacks positions %s",
                family,
                reference.experiment_positions[:2],
            )
            skipped_families.append(family)
            continue
        simulation_markers = _ensure_marker_table(
            reference.dataset,
            layer="sim",
            marker_role="sim",
            data_root=data_root,
            analysis_root=analysis_root,
            file_workers=file_workers,
            plot_workers=plot_workers,
            project_defaults=project_defaults,
        )
        try:
            comparison = build_tuning_family_comparison(
                simulation_markers,
                baseline_markers,
                current_markers,
                reference=reference,
                phase_reference=campaign.phase,
                design_r_c_mm=campaign.design_r_c_mm,
            )
        except PhaseRadiusMappingError as error:
            reason = str(error)
            logger.warning(
                "Skipping %s r_c mapping: %s",
                family,
                reason,
            )
            skipped_families.append(family)
            skipped_family_reasons[family] = reason
            continue
        family_tables = {
            "anchor_chk": comparison.anchor_check,
            "rc_fit": comparison.rc_fit,
            "phase_cmp": comparison.phase_cmp,
        }
        for name, table in family_tables.items():
            path = output_table_dir / f"{family}_{name}.csv"
            table.to_csv(path, index=False)
            table_paths[f"{family}_{name}"] = path

        phase_rc_map = plot_phase_rc_map(
            comparison.simulation_line,
            comparison.rc_fit,
            output_figure_dir / f"{family}_phase_rc_map.png",
        )
        current_label = (
            f"Torque {current_state.torque_nm:g}"
            if current_state.torque_nm is not None
            else "Current"
        )
        phase_cmp_bars = plot_phase_cmp_bars(
            comparison.phase_cmp,
            output_figure_dir / f"{family}_phase_cmp_bars.png",
            current_label=current_label,
        )
        figure_paths[f"{family}_phase_rc_map"] = phase_rc_map
        figure_paths[f"{family}_phase_cmp_bars"] = phase_cmp_bars
        completed_families.append(family)

    metadata: dict[str, object] = {
        "baseline_state_id": campaign.baseline_state_id,
        "current_state_id": campaign_match.state_id,
        "families": completed_families,
        "skipped_families": skipped_families,
        "skipped_family_reasons": skipped_family_reasons,
        "radius_interpretation": (
            "simulation-equivalent r_c coordinates; not physical bolt travel"
        ),
        "port_extension_reapplied": False,
    }
    register_tuning_cmp(
        Path(current_result.manifest_path),
        tables=table_paths,
        figures=figure_paths,
        metadata=metadata,
    )
    return TuningCmpResult(
        tables=table_paths,
        figures=figure_paths,
        families=tuple(completed_families),
        skipped_families=tuple(skipped_families),
    )


def _ensure_marker_table(
    dataset: str,
    *,
    layer: str,
    marker_role: str,
    data_root: Path,
    analysis_root: Path,
    file_workers: int,
    plot_workers: int,
    project_defaults: ProjectDefaults,
) -> pd.DataFrame:
    output_dir = analysis_root / dataset
    marker_path = output_dir / "tables" / "marker_pts.csv"
    if not marker_path.is_file():
        logger.info("Preparing marker table for tuning reference dataset %s", dataset)
        result = run_folder_analysis(
            sparameter_path=data_root / layer / dataset,
            output_dir=output_dir,
            marker_role=marker_role,
            data_root=data_root,
            file_workers=file_workers,
            plot_workers=plot_workers,
            tables_only=True,
            project_defaults=project_defaults,
        )
        marker_path = _marker_table_path(result)
    return pd.read_csv(marker_path)


def _marker_table_path(result: RunResult) -> Path:
    path = result.tables.get("marker_pts")
    if path is None:
        path = Path(result.output_dir) / "tables" / "marker_pts.csv"
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"Marker table is missing: {path}")
    return path


def _table_contains_positions(
    marker_table: pd.DataFrame,
    positions: tuple[float, ...],
) -> bool:
    if "tune_position" not in marker_table:
        return False
    available = pd.to_numeric(marker_table["tune_position"], errors="coerce")
    return all(np.isclose(available, position, atol=1e-6).any() for position in positions)


def _simulation_rc_line(
    marker_table: pd.DataFrame,
    *,
    marker_names: list[str],
) -> pd.DataFrame:
    _require_columns(
        marker_table,
        ("sim_r_c", "marker_name", "s_phase_deg"),
        "simulation_marker_table",
    )
    if "sim_w_c" in marker_table:
        widths = pd.to_numeric(marker_table["sim_w_c"], errors="coerce").dropna()
        if widths.nunique() > 1:
            raise ValueError(
                "Automatic tuning comparison requires a one-dimensional r_c line; "
                "sim_w_c contains multiple values"
            )
    line = marker_table[
        marker_table["marker_name"].astype(str).isin(marker_names)
    ].loc[:, ["sim_r_c", "marker_name", "s_phase_deg"]].copy()
    line["sim_r_c"] = pd.to_numeric(line["sim_r_c"], errors="coerce")
    line["s_phase_deg"] = pd.to_numeric(line["s_phase_deg"], errors="coerce")
    line = line[
        np.isfinite(line["sim_r_c"]) & np.isfinite(line["s_phase_deg"])
    ].copy()
    line = (
        line.sort_values(["marker_name", "sim_r_c"], kind="mergesort")
        .drop_duplicates(["marker_name", "sim_r_c"], keep="last")
        .reset_index(drop=True)
    )
    if line.empty:
        raise ValueError("simulation marker table has no usable one-dimensional r_c line")
    return line


def _common_delta_bounds_um(
    simulation_line: pd.DataFrame,
    *,
    marker_names: list[str],
    design_r_c_mm: float,
) -> tuple[float, float]:
    lower_bounds: list[float] = []
    upper_bounds: list[float] = []
    for marker_name in marker_names:
        radii = simulation_line.loc[
            simulation_line["marker_name"] == marker_name,
            "sim_r_c",
        ]
        if radii.empty:
            raise ValueError(f"Simulation r_c line is missing marker {marker_name!r}")
        lower_bounds.append(float(radii.min()))
        upper_bounds.append(float(radii.max()))
    common_minimum = max(lower_bounds)
    common_maximum = min(upper_bounds)
    if not common_minimum <= design_r_c_mm <= common_maximum:
        raise ValueError(
            f"design r_c {design_r_c_mm:g} mm is outside the common simulation range"
        )
    return (
        (common_minimum - design_r_c_mm) * 1e3,
        (common_maximum - design_r_c_mm) * 1e3,
    )


def _select_position_markers(
    marker_table: pd.DataFrame,
    *,
    position: float,
    port_extension_applied: bool,
) -> pd.DataFrame:
    _require_columns(marker_table, REQUIRED_MARKER_COLUMNS, "marker_table")
    table = marker_table.copy()
    table["tune_position"] = pd.to_numeric(table["tune_position"], errors="coerce")
    table["s_phase_deg"] = pd.to_numeric(table["s_phase_deg"], errors="coerce")
    selected = table[np.isclose(table["tune_position"], position, atol=1e-6)].copy()
    selected = selected[np.isfinite(selected["s_phase_deg"])].copy()
    if port_extension_applied:
        extended = selected[
            selected["source_file"].astype(str).str.contains(
                r"(?:^|_)portE(?:[._]|$)",
                case=False,
                regex=True,
            )
        ]
        if not extended.empty:
            selected = extended
    duplicated = selected["marker_name"].duplicated(keep=False)
    if duplicated.any():
        names = sorted(selected.loc[duplicated, "marker_name"].astype(str).unique())
        raise ValueError(
            f"Multiple traces remain at position {position:g} for markers {names}"
        )
    if selected.empty:
        raise ValueError(f"No marker phases at position {position:g}")
    return selected.reset_index(drop=True)


def _wrap180(angle_deg: np.ndarray | float) -> np.ndarray:
    return (np.asarray(angle_deg, dtype=float) + 180.0) % 360.0 - 180.0


def _require_columns(
    table: pd.DataFrame,
    columns: tuple[str, ...],
    table_name: str,
) -> None:
    missing = [column for column in columns if column not in table]
    if missing:
        raise ValueError(f"{table_name} is missing required columns: {missing}")
