"""Check assembly of CST-Run-Analyze batch exports into a navigator-indexed dataset."""

import hashlib
import json
from pathlib import Path

import pytest

from deflector_tuning.data_loading.cst_batch_delivery import (
    assemble_delivery,
    read_cst_navigator,
    read_sha256_manifest,
    reference_run_id,
)
from deflector_tuning.data_loading.readers.touchstone_reader import read_touchstone

REFERENCE_NAVIGATOR = ('" 3D Run ID"\t"NumDepth"\t"NumTune"\r\n"1"\t"0.5"\t"5"\r\n"2"\t"0.5"\t"4"\r\n'
                       '"12"\t"1"\t"5"\r\n')


def _export(depth: str) -> str:
    return "\n".join([
        "! TOUCHSTONE file generated by CST MICROWAVE STUDIO",
        f"! Project name: run-{depth}.cst",
        f"! Parameters = {{NumCell=9; NumDepth={depth}; NumTune=5; R_plunger=8}}",
        "! Touchstone port assignment:",
        '! Touchstone port 1 = CST MWS port 1 ("")',
        '! Touchstone port 2 = CST MWS port 2 ("")',
        "# GHz S RI R 0",
        "2.84 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8",
        "2.85 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8",
    ]) + "\n"


def _batch(root: Path, name: str, depths: list[str]) -> Path:
    batch = root / "data" / "sim" / name
    batch.mkdir(parents=True)
    runs, navigator = [], ["run_id,label,status,final_mesh_cells,elapsed_seconds,export"]
    for index, depth in enumerate(depths, 1):
        label, folder = f"seq-D{depth}", f"r{index:02d}-seq-D{depth}"
        export = f"{folder}.s2p"
        (batch / export).write_text(_export(depth), encoding="utf-8")
        (batch / folder).mkdir()
        run = {"id": index, "label": label, "folder": folder, "parameters": {"NumDepth": depth}}
        result = {"run": run, "status": "complete", "export": export, "seed_sha256": "seed",
                  "export_sha256": hashlib.sha256((batch / export).read_bytes()).hexdigest(),
                  "final_mesh_cells": 100, "adaptive_mesh_converged": False, "broadband_converged": True}
        (batch / folder / "result.json").write_text(json.dumps(result), encoding="utf-8")
        runs.append(run)
        navigator.append(f"{index},{label},complete,100,1.0,{export}")
    (batch / "result_navigator.csv").write_text("\n".join(navigator) + "\n", encoding="utf-8")
    (batch / "spec.json").write_text(json.dumps({"batch": name, "frequency_GHz": [2.84, 2.85, 2],
                                                 "runs": runs}), encoding="utf-8")
    files = sorted(path for path in batch.rglob("*") if path.is_file())
    (batch / "MANIFEST.sha256").write_text("".join(
        f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.relative_to(batch).as_posix()}\n"
        for path in files), encoding="utf-8")
    return batch


def _config(depths: list[float]) -> dict:
    return {"output_dataset": "data/sim/sim_sweep_000000_delivery_ports_swapped", "description": "test",
            "file_stem": "delivery", "reference_navigator": "data/sim/reference/result_navigator.csv",
            "varying_parameter": "NumDepth", "expected_values": depths,
            "batches": [{"dataset": "data/sim/sim_sweep_000000_batch", "label_pattern": "^seq-D",
                         "input_port_touchstone_index": 2}]}


@pytest.fixture
def workspace(tmp_path: Path) -> Path:
    reference = tmp_path / "data" / "sim" / "reference"
    reference.mkdir(parents=True)
    (reference / "result_navigator.csv").write_bytes(REFERENCE_NAVIGATOR.encode("utf-8"))
    _batch(tmp_path, "sim_sweep_000000_batch", ["0.5", "1"])
    return tmp_path


def test_delivery_swaps_ports_and_names_files_by_reference_run_id(workspace: Path) -> None:
    result = assemble_delivery(workspace, _config([0.5, 1]), "config.json")
    output = result["output"]
    assert sorted(path.name for path in output.glob("*.s2p")) == ["delivery_1.s2p", "delivery_12.s2p"]
    raw = read_touchstone(workspace / "data/sim/sim_sweep_000000_batch/r01-seq-D0.5.s2p")
    delivered = read_touchstone(output / "delivery_1.s2p")
    assert delivered.values == [list(reversed(row)) for row in raw.values]
    assert '! Touchstone port 1 = CST MWS port 2 ("")' in (output / "delivery_1.s2p").read_text(encoding="utf-8")


def test_delivery_navigator_keeps_cst_layout_and_reference_columns(workspace: Path) -> None:
    output = assemble_delivery(workspace, _config([0.5, 1]), "config.json")["output"]
    text = (output / "result_navigator.csv").read_bytes().decode("utf-8")
    assert text == '" 3D Run ID"\t"NumDepth"\t"NumTune"\r\n"1"\t"0.5"\t"5"\r\n"12"\t"1"\t"5"\r\n'
    assert b"\r" not in (output / "MANIFEST.sha256").read_bytes()
    manifest = read_sha256_manifest(output / "MANIFEST.sha256")
    assert set(manifest) == {"README.md", "delivery_1.s2p", "delivery_12.s2p",
                             "result_navigator.csv", "source_map.csv"}


def test_delivery_rejects_a_file_that_differs_from_the_batch_manifest(workspace: Path) -> None:
    export = workspace / "data/sim/sim_sweep_000000_batch/r02-seq-D1.s2p"
    export.write_text(export.read_text(encoding="utf-8").replace("1.8", "1.9"), encoding="utf-8")
    with pytest.raises(ValueError, match="Manifest hash mismatch"):
        assemble_delivery(workspace, _config([0.5, 1]), "config.json")


def test_delivery_rejects_missing_configured_states(workspace: Path) -> None:
    with pytest.raises(ValueError, match="differ from configured"):
        assemble_delivery(workspace, _config([0.5, 1, 1.5]), "config.json")


def test_reference_run_id_requires_one_matching_row(workspace: Path) -> None:
    rows = read_cst_navigator(workspace / "data/sim/reference/result_navigator.csv")
    assert reference_run_id(rows, {"NumDepth": 0.5, "NumTune": 4})[" 3D Run ID"] == "2"
    with pytest.raises(ValueError, match="found 0"):
        reference_run_id(rows, {"NumDepth": 0.5, "NumTune": 3})
