"""Reproduce held-out CST reflection predictions and their source manifest.

Defaults select regular cell/iris shorting sequences from the full-structure
export. The empirical recurrence is not an independent coupler-matching test.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import asdict, replace
from datetime import datetime, timezone
import hashlib
import json
import logging
from pathlib import Path
import re
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from deflector_tuning.analysis.periodic_reflection import evaluate_held_out_sequence
from deflector_tuning.data_loading.loaders.sim_loader import _read_cst_parameter_header
from deflector_tuning.data_loading.readers.touchstone_reader import read_touchstone
from deflector_tuning.data_loading.source_layer import DataLayer, detect_data_layer
from deflector_tuning.visualization.lps_paper_style import apply_lps_style, finish_axes, save_paper_figure


LOGGER = logging.getLogger(__name__)
MARKER_NAMES = ("f_2pi3", "f_mean", "f_pi2")
MARKER_LABELS = (r"$f_{2\pi/3}$", r"$f_m$", r"$f_{\pi/2}$")
DEFAULT_MARKERS_GHZ = (2.8571160335532, 2.8672804543714, 2.8774448751896)
DEFAULT_CONFIG = ROOT / "config" / "paper_cst_20261003.json"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _metadata(path: Path) -> dict:
    comments = []
    option_line = None
    with path.open(encoding="utf-8") as stream:
        for raw in stream:
            line = raw.strip()
            if line.startswith("!"):
                comments.append(line)
            elif line.startswith("#"):
                option_line = line
                break
    parameters = {name.removeprefix("sim_"): value
                  for name, value in _read_cst_parameter_header(path).items()}
    project = next((line.split(":", 1)[1].strip() for line in comments
                    if line.startswith("! Project name:")), None)
    ports = [line for line in comments if re.match(r"!\s*Touchstone port\s+\d+\s*=", line)]
    if not project or not option_line or "NumDepth" not in parameters:
        raise ValueError(f"Incomplete CST metadata: {path.name}")
    if not any("generated by CST" in line for line in comments):
        raise ValueError(f"Not an identified CST export: {path.name}")
    return {"parameters": parameters, "project": project, "port_assignments": ports,
            "option_line": option_line, "header_comments": comments}


def _navigator(path: Path) -> dict[int, dict]:
    with path.open(encoding="utf-8-sig", newline="") as stream:
        rows = [{name.strip(): value.strip() for name, value in row.items()}
                for row in csv.DictReader(stream, delimiter="\t")]
    result = {}
    for row in rows:
        run_id = int(row["3D Run ID"])
        if run_id in result:
            raise ValueError(f"Duplicate navigator run ID {run_id}")
        result[run_id] = row
    return result


def source_case(config: dict) -> dict:
    """Return the scattering case named by the config's ``periodic_diagnostic`` section."""
    case_id = config["periodic_diagnostic"]["case"]
    matches = [case for case in config["cases"] if case["id"] == case_id]
    if len(matches) != 1:
        raise ValueError(f"Expected one configured case {case_id!r}")
    return matches[0]


def _load_sequences(source: Path, depth_groups: dict[str, list[float]], markers: list[float],
                    expected_num_tune: float, *, require_same_project: bool = True,
                    ) -> tuple[dict, list[dict], dict]:
    """Route to simulation data and match source headers to the navigator.

    With ``require_same_project=False`` (one CST project per run) the project
    name is recorded per source and excluded from the fixed-metadata check.
    """
    if detect_data_layer(source) is not DataLayer.SIM:
        raise ValueError("This CST diagnostic accepts only data/sim sources")
    navigator_path = source / "result_navigator.csv"
    navigator = _navigator(navigator_path)
    wanted = {depth for depths in depth_groups.values() for depth in depths}
    selected = {}
    excluded = []
    baseline_metadata = None
    baseline_grid = None
    for path in sorted(source.glob("*.s2p")):
        metadata = _metadata(path)
        parameters = metadata["parameters"]
        depth = float(parameters["NumDepth"])
        if depth not in wanted:
            excluded.append({"file": path.name, "NumDepth": depth})
            continue
        if depth in selected:
            raise ValueError(f"Multiple exports for NumDepth={depth}")
        if parameters.get("NumTune") != expected_num_tune:
            raise ValueError(f"Unexpected NumTune at NumDepth={depth}")
        match = re.search(r"_(\d+)\.s2p$", path.name)
        if match is None:
            raise ValueError(f"No navigator run suffix in {path.name}")
        run_id = int(match.group(1))
        row = navigator[run_id]
        for name in ("NumDepth", "NumTune"):
            if float(row[name]) != parameters[name]:
                raise ValueError(f"Navigator/header mismatch in {path.name}: {name}")
        if metadata["port_assignments"] != [
            '! Touchstone port 1 = CST MWS port 2 ("")',
            '! Touchstone port 2 = CST MWS port 1 ("")',
        ]:
            raise ValueError(f"Expected swapped CST port assignments: {path.name}")
        ignored = {"header_comments"} if require_same_project else {"header_comments", "project"}
        fixed = {key: value for key, value in metadata.items() if key not in ignored}
        fixed["parameters"] = {key: value for key, value in parameters.items()
                               if key not in {"NumDepth", "DepthPlunger"}}
        if baseline_metadata is None:
            baseline_metadata = fixed
        elif fixed != baseline_metadata:
            raise ValueError(f"Non-state geometry or port metadata changes: {path.name}")
        parsed = read_touchstone(path)
        if parsed.header.parameter != "S" or parsed.header.reference_ohm != 0:
            raise ValueError(f"Expected unrenormalized CST S data with R 0: {path.name}")
        scales = {"Hz": 1e-9, "kHz": 1e-6, "MHz": 1e-3, "GHz": 1.0}
        frequencies = np.asarray(parsed.frequency) * scales[parsed.header.frequency_unit]
        values = np.asarray(parsed.values, dtype=complex)[:, 0]
        if (len(frequencies) == 0 or not np.isfinite(frequencies).all()
                or not np.isfinite(values).all() or np.any(np.diff(frequencies) <= 0)):
            raise ValueError(f"Invalid exported frequency grid or complex data: {path.name}")
        if baseline_grid is None:
            baseline_grid = frequencies
        elif not np.array_equal(baseline_grid, frequencies):
            raise ValueError(f"Exported frequency grid differs: {path.name}")
        samples = []
        for marker in markers:
            if not np.isfinite(marker) or not frequencies[0] <= marker <= frequencies[-1]:
                raise ValueError(f"Marker lies outside exported frequencies: {marker}")
            index = int(np.argmin(np.abs(frequencies - marker)))
            samples.append({"requested_frequency_GHz": marker,
                            "actual_frequency_GHz": float(frequencies[index]),
                            "frequency_error_kHz": float((frequencies[index] - marker) * 1e6),
                            "sample_index_zero_based": index,
                            "real": float(values[index].real), "imag": float(values[index].imag)})
        selected[depth] = {"path": path.relative_to(ROOT).as_posix(), "sha256": _sha256(path),
                           "run_id": run_id, "navigator_row": row, "metadata": metadata,
                           "touchstone_header": asdict(parsed.header),
                           "frequency_sample_count": len(frequencies), "samples": samples}
    if set(selected) != wanted:
        raise ValueError(f"Missing requested NumDepth states: {sorted(wanted - set(selected))}")
    sequence_arrays = {}
    for name, depths in depth_groups.items():
        spacing = np.diff(depths)
        if (len(depths) < 5 or not np.isfinite(depths).all()
                or not np.allclose(spacing, spacing[0], rtol=0, atol=1e-12)
                or spacing[0] <= 0):
            raise ValueError("Sequences must have at least five increasing equally spaced depths")
        sequence_arrays[name] = np.array([
            [complex(sample["real"], sample["imag"]) for sample in selected[depth]["samples"]]
            for depth in depths
        ])
    audit = {"path": navigator_path.relative_to(ROOT).as_posix(), "sha256": _sha256(navigator_path),
             "selected_headers_match_navigator": True, "fixed_metadata_consistent": True,
             "project_name_policy": ("identical project required" if require_same_project
                                     else "one CST project per run; names recorded per source"),
             "excluded_exported_states": excluded}
    return sequence_arrays, [selected[depth] for depth in sorted(selected)], audit


def _write_csv(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def _plot_predictions(rows: list[dict], summaries: list[dict], marker_values: list[float],
                      depth_groups: dict, training_count: int, fig_dir: Path) -> list[Path]:
    apply_lps_style()
    fig, axes = plt.subplots(1, 3, figsize=(7.08, 2.9), sharey=True)
    colors = {"cell": "C0", "iris": "C1"}
    markers = {"cell": "o", "iris": "s"}
    labels = {"cell": "Cell-centered", "iris": "Iris-centered"}
    min_depth = min(row["NumDepth"] for row in rows)
    max_depth = max(row["NumDepth"] for row in rows)
    for panel, (ax, name, label, requested) in enumerate(zip(axes, MARKER_NAMES, MARKER_LABELS, marker_values)):
        for sequence in depth_groups:
            selected = [row for row in rows if row["marker"] == name and row["sequence"] == sequence]
            ax.plot([row["NumDepth"] for row in selected],
                    [row["absolute_phase_error_deg"] for row in selected],
                    color=colors[sequence], marker=markers[sequence], markersize=5,
                    markerfacecolor="white", markeredgewidth=1.3,
                    linewidth=2, label=labels[sequence])
        ax.set_title(f"({chr(97 + panel)}) {label}", pad=8)
        ax.set_xlabel("NumDepth")
        ax.set_xticks(np.arange(np.floor(min_depth), np.floor(max_depth) + 1))
        ax.set_xlim(np.floor(min_depth) - 0.1, max_depth + 0.3)
    # Fix the shared y range only after every panel is drawn; fixing it inside the
    # loop froze the top at the first panel's data and clipped later panels.
    axes[0].set_ylim(bottom=0)
    axes[0].set_ylabel("Phase prediction error [deg]")
    fig.legend(*axes[0].get_legend_handles_labels(), loc="upper center", ncol=2,
               bbox_to_anchor=(0.55, 1.02))
    fig.subplots_adjust(left=0.09, right=0.99, bottom=0.19, top=0.73, wspace=0.18)
    for ax in axes:
        finish_axes(ax)
    outputs = []
    for suffix in ("pdf", "png"):
        path = fig_dir / f"fig06-periodic-prediction.{suffix}"
        save_paper_figure(fig, path, metadata={"Title": "Held-out empirical reflection recurrence"})
        outputs.append(path)
    plt.close(fig)
    return outputs


def build_diagnostic(args: argparse.Namespace) -> dict:
    """Write a reproducible six-case held-out diagnostic from raw CST exports."""
    config = json.loads(args.config.read_text(encoding="utf-8"))
    case = source_case(config)
    if args.source is None:
        args.source = case["dataset"]
    source = (ROOT / args.source).resolve()
    destination = (ROOT / args.manuscript_dir).resolve()
    depth_groups = {"cell": args.cell_depths, "iris": args.iris_depths}
    arrays, sources, navigator = _load_sequences(
        source, depth_groups, args.marker_ghz, args.num_tune,
        require_same_project=case.get("require_same_project", True))
    predictions, summaries, sequence_audits = [], [], []
    for sequence, depths in depth_groups.items():
        for marker_index, (name, requested) in enumerate(zip(MARKER_NAMES, args.marker_ghz)):
            values = arrays[sequence][:, marker_index]
            result = evaluate_held_out_sequence(values, training_transition_count=args.training_transitions)
            fit = result.fit
            held_depths = depths[result.training_state_count:]
            first_source = next(item for item in sources if item["metadata"]["parameters"]["NumDepth"] == depths[0])
            actual_frequency = first_source["samples"][marker_index]["actual_frequency_GHz"]
            identity = {"sequence": sequence, "marker": name, "requested_frequency_GHz": requested,
                        "actual_frequency_GHz": actual_frequency}
            for step, (depth, observed, predicted, phase_error, relative_error) in enumerate(zip(
                    held_depths, result.observed, result.predicted, result.phase_error_deg,
                    result.relative_complex_error), 1):
                origin = next(item for item in sources if item["metadata"]["parameters"]["NumDepth"] == depth)
                predictions.append({**identity, "NumDepth": depth, "prediction_step": step,
                                    "observed_real": float(observed.real), "observed_imag": float(observed.imag),
                                    "predicted_real": float(predicted.real), "predicted_imag": float(predicted.imag),
                                    "circular_phase_error_deg": float(phase_error),
                                    "absolute_phase_error_deg": float(abs(phase_error)),
                                    "relative_complex_error": float(relative_error),
                                    "source": origin["path"], "source_sha256": origin["sha256"]})
            summary = {**identity, "training_transition_count": fit.transition_count,
                       "training_state_count": result.training_state_count, "training_end_NumDepth": depths[args.training_transitions],
                       "held_out_state_count": len(held_depths), "design_rank": fit.design_rank,
                       "sigma1": fit.singular_values[0], "sigma2": fit.singular_values[1],
                       "sigma3": fit.singular_values[2], "sigma4": fit.sigma4,
                       "condition_sigma1_over_sigma3": fit.condition_sigma1_over_sigma3,
                       "normalized_determinant": fit.normalized_determinant,
                       "mean_absolute_phase_error_deg": float(np.mean(np.abs(result.phase_error_deg))),
                       "rms_phase_error_deg": float(np.sqrt(np.mean(result.phase_error_deg**2))),
                       "max_absolute_phase_error_deg": float(np.max(np.abs(result.phase_error_deg))),
                       "mean_relative_complex_error": float(np.mean(result.relative_complex_error)),
                       "rms_relative_complex_error": float(np.sqrt(np.mean(result.relative_complex_error**2))),
                       "max_relative_complex_error": float(np.max(result.relative_complex_error))}
            summaries.append(summary)
            sequence_audits.append({**summary, "NumDepth": depths,
                                    "observed_real": values.real.tolist(), "observed_imag": values.imag.tolist(),
                                    "training_indices_zero_based": list(range(result.training_state_count)),
                                    "held_out_indices_zero_based": list(range(result.training_state_count, len(depths))),
                                    "matrix_real": fit.matrix.real.tolist(), "matrix_imag": fit.matrix.imag.tolist(),
                                    "prediction_real": result.predicted.real.tolist(),
                                    "prediction_imag": result.predicted.imag.tolist()})
            LOGGER.info("%s %s: held-out mean |phase error| %.6f deg; mean relative complex error %.6g; sigma1/sigma3 %.6g",
                        sequence, name, summary["mean_absolute_phase_error_deg"],
                        summary["mean_relative_complex_error"], fit.condition_sigma1_over_sigma3)
    for subdir in ("fig", "tables", "docs/evidence"):
        (destination / subdir).mkdir(parents=True, exist_ok=True)
    prediction_path = destination / "tables/paper-periodic-predictions.csv"
    summary_path = destination / "tables/paper-periodic-summary.csv"
    _write_csv(prediction_path, predictions)
    _write_csv(summary_path, summaries)
    figures = _plot_predictions(predictions, summaries, args.marker_ghz, depth_groups,
                                args.training_transitions, destination / "fig")
    for item in [*sources, navigator]:
        if _sha256(ROOT / item["path"]) != item["sha256"]:
            raise RuntimeError(f"Source changed during diagnostic: {item['path']}")
    code_paths = [Path(__file__), args.config.resolve(), ROOT / "deflector_tuning/analysis/periodic_reflection.py",
                  ROOT / "tests/test_periodic_reflection.py",
                  ROOT / "deflector_tuning/data_loading/readers/touchstone_reader.py",
                  ROOT / "deflector_tuning/data_loading/loaders/sim_loader.py",
                  ROOT / "deflector_tuning/visualization/lps_paper_style.py",
                  ROOT / "config/lps_publication_style.json"]
    manifest = {
        "generated_utc": datetime.now(timezone.utc).isoformat(), "schema_version": 1,
        "scope": "Empirical reflection recurrence and held-out depth prediction; not coupler-matching validation",
        "model": "Gamma_next = (a Gamma + b)/(c Gamma + d)",
        "fit_design_row": "[Gamma, 1, -Gamma*Gamma_next, -Gamma_next]",
        "fit_solver": "complex SVD with full_matrices=True; coefficient vector = Vh[-1].conj()",
        "fit_interpretation": "Three transitions are exactly determined; training agreement is not validation. A 3x4 design has three reported singular values and one implicit right-null dimension. sigma1/sigma3 is a constrained-subspace condition measure; it is not a null gap.",
        "normalized_determinant_definition": "abs(det(M))/norm(M, 'fro')**2",
        "prediction_protocol": "Start at the last training state and propagate to all remaining depths without resetting to observations",
        "phase_error_definition": "wrap_deg(arg(predicted)-arg(observed)) in [-180,180)",
        "relative_complex_error_definition": "abs(predicted-observed)/abs(observed)",
        "statistics_scope": "Held-out states only",
        "port_and_normalization": "Exported S11 corresponds to original CST port 2; R 0 denotes CST unrenormalized export metadata, not a physical 50-ohm reference. No impedance conversion or renormalization applied.",
        "configuration": {"source": args.source, "NumTune": args.num_tune, "depth_sequences": depth_groups,
                          "training_transitions": args.training_transitions,
                          "requested_marker_frequencies_GHz": dict(zip(MARKER_NAMES, args.marker_ghz)),
                          "sampling": "nearest exported sample; no interpolation"},
        "dependencies": {"python": sys.version, "numpy": np.__version__, "matplotlib": matplotlib.__version__},
        "navigator": navigator, "sources": sources, "sequences": sequence_audits,
        "source_hashes_unchanged_after_generation": True,
        "code": [{"path": path.relative_to(ROOT).as_posix(), "sha256": _sha256(path)} for path in code_paths],
        "outputs": [{"path": path.relative_to(destination).as_posix(), "sha256": _sha256(path)}
                    for path in [prediction_path, summary_path, *figures]],
    }
    manifest_path = destination / "docs/evidence/periodic-diagnostic-manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    LOGGER.info("Wrote %d held-out predictions, %d summaries and manifest to %s", len(predictions), len(summaries), destination)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG,
                        help="Paper CST config; its periodic_diagnostic.case selects the source")
    parser.add_argument("--source", default=None,
                        help="Simulation directory relative to the repository (default: from --config)")
    parser.add_argument("--manuscript-dir", default="../TDC-AcademicPaper")
    parser.add_argument("--marker-ghz", nargs=3, type=float, default=list(DEFAULT_MARKERS_GHZ))
    parser.add_argument("--cell-depths", nargs="+", type=float, default=np.arange(1.5, 10, 1).tolist())
    parser.add_argument("--iris-depths", nargs="+", type=float, default=np.arange(2, 10, 1).tolist())
    parser.add_argument("--num-tune", type=float, default=5)
    parser.add_argument("--training-transitions", type=int, default=3)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    logging.getLogger("fontTools.subset").setLevel(logging.WARNING)
    build_diagnostic(args)


if __name__ == "__main__":
    main()
